SPOTIFY_API_CLIENT_ID = 'ENTER YOUR SPOTIFY KEY OVER HERE'
SPOTIFY_API_SECRET = 'ENTER YOUR SPOTIFY KEY OVER HERE'
LASTFM_API_KEY = 'ENTER YOUR LAST.FM KEY OVER HERE'
LASTFM_SHARED_SECRET = 'ENTER YOUR LAST.FM KEY OVER HERE'
